@isTest
public class chat2AITest 
{
    static testMethod void testIt()
    {
        Test.startTest();
        chat2AI.Button b = new chat2AI.Button();
        chat2AI.Action a= new chat2AI.Action();
        chat2AI.Template t= new chat2AI.Template();
        chat2AI.Option o= new chat2AI.Option();
        chat2AI.Data d = new chat2AI.Data();
        chat2AI.Attr at = new chat2AI.Attr();
        Test.stopTest();
    }
}